// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVfYnExulmdHupmiqbwGbPAxMd7Mhixsk',
    appId: '1:131716867531:web:d774caee18a0a40a4c024e',
    messagingSenderId: '131716867531',
    projectId: 'project1-ae4c6',
    authDomain: 'project1-ae4c6.firebaseapp.com',
    databaseURL: 'https://project1-ae4c6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'project1-ae4c6.appspot.com',
    measurementId: 'G-M1ZF4KG4TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbSASNyy3FVsq1aMUHTmp-Rn9A0OKJ_oo',
    appId: '1:131716867531:android:42f177e3ebb3dc044c024e',
    messagingSenderId: '131716867531',
    projectId: 'project1-ae4c6',
    databaseURL: 'https://project1-ae4c6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'project1-ae4c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyG_McJUAHpMpfxi40cfU_vnPacfBaDF0',
    appId: '1:131716867531:ios:a5207e079b84f3d44c024e',
    messagingSenderId: '131716867531',
    projectId: 'project1-ae4c6',
    databaseURL: 'https://project1-ae4c6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'project1-ae4c6.appspot.com',
    iosClientId: '131716867531-hol05mqc79i4k1m86gtpi5292hl61gt4.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );
}
